<?php /* @var $block \Barzahlen\Payment\Block\Success */?>
<?php
$order = $block->getOrder();
?>
<div class="checkout-success">

    <?php if($order->getIncrementId()):?>
        <?php if ($block->getCustomerId()) :?>
            <p><?php echo __('Your order number is: '.$order->getIncrementId().')') ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.',$order->getIncrementId()) ?></p>
        <?php endif;?>
        <p><?php echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?php if($order->getPayment()->getMethod() == "barzahlen_gateway"):?>
        <button class="bz-checkout-btn"><?php echo __('Show Barzahlen.de payment slip') ?></button>

        <?php echo $block->getPaymentSlip(); ?>
    <?php endif; ?>

</div>


